logging:
  level:
    root: ${LEVEL_LOG}
spring:
  application:
    name: skye-portfolio-backend
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always
server:
  port: ${PORT}
  address: ${ADDRESS}

rate-limit:
  enabled: true
  capacity: 10
  refill-tokens: 10
  refill-duration-minutes: 1
  cache-max-size: 100
  cache-expire-hours: 1
  header-prefix: X-RateLimit

mailgun:
  domain: ${MAILGUN_DOMAIN}
  api-key:  ${API_MAILGUN_KEY}
  from-email: ${ICLOUD_SKYE_EMAIL}